### ISSUE TITLE
iOS Issue : Blocked a frame with origin "http://x.y.z" from accessing a frame with origin "http://imasdk.googleapis.com". Protocols, domains, and ports must match.

### ISSUE THREAD

**Issue by Joan-Rojo1** [googleads/videojs-ima#264]
Hi there,

We are working on integrating VIdeo IMA HTML5 with VideoJS and it seeams to work fine on Android devices and desktop under mobile UA. But, testing on an iPhone 6/Safari the player get totally blocked and doesnt play anything. On the console we see errors as the following:

Blocked a frame with origin "http://prem.publico.es" from accessing a frame with origin "http://imasdk.googleapis.com". Protocols, domains, and ports must match.

You can take as example the URL:

http://prem.publico.es/publicotv/577459/un-pasajero-salta-a-la-pista-del-aeropuerto-de-madrid

And the tagAd is created dinamically passing different tracking parameters but always following the same form, as example:

http://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=/43954681/Publico/mobile&cust_params=br%3D2%26dt%3D1%26adunit%3DPublico/mobile%26Country%3DES&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=http%3A%2F%2Fprem.publico.es%2Fpublicotv%2F577459%2Fun-pasajero-salta-a-la-pista-del-aeropuerto-de-madrid&description_url=http%3A%2F%2Fprem.publico.es%2Fpublicotv%2F577459%2Fun-pasajero-salta-a-la-pista-del-aeropuerto-de-madrid&correlator=

We really appreciate any help.

Thanks in advance & regards,

Joan

**Comment by shawnbuso** [comment]
Hey there,

Are you using the latest version of the plugin? We fixed some iPhone-related issues recently hat you may now be running into.

I think the "blocked frame with origin" error is a red herring - we see that in our samples as well, and they work fine. I tested your tag (http://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=/43954681/Publico/mobile&cust_params=br%3D2%26dt%3D1%26adunit%3DPublico/mobile%26Country%3DES&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=http%3A%2F%2Fprem.publico.es%2Fpublicotv%2F577432%2Fla-novia-mas-feliz-en-una-boda-sin-novio&description_url=http%3A%2F%2Fprem.publico.es%2Fpublicotv%2F577432%2Fla-novia-mas-feliz-en-una-boda-sin-novio&correlator=) in our [advanced sample](http://googleads.github.io/videojs-ima/examples/advanced/) and it does work there, and that's using the latest plugin version, so an update may fix your issue.

**Comment by shawnbuso** [comment]
Did that work for you? Let me know so I can close out the issue - thanks!

**Comment by Joan-Rojo1** [comment]
Hi Shawn, I have to test it yet and I will let you know in the next few days. Thanks!

**Comment by Joan-Rojo1** [comment]
Hi there,

I'm still getting the blocked iframe error but the video is being played and the vast is shown, if not empty of course. I think that the issue for not playing the video was related to this:

http://stackoverflow.com/questions/37158342/video-js-google-ima-on-mobile-devices-tap-event-causing-errors

I guess I can close the issue by now and reopen it in case.

Thanks for your support Shawn, best regards!
