### ISSUE TITLE
Overlay Ad

### ISSUE THREAD

**Issue by onix-sergey** [googleads/videojs-ima#685]
Hi,

Please advise how to correctly implement "midrroll" and "overlay" ads. 
As far as I understand to show "overlay" ads, I need manually resize the ads container and before show midroll resize it back to the original size. Or don't use plugin and create one more ad containers.
Is it correct approach? or there is more friendly way?

By "overlay" I mean something like this:
![overlay](https://cloud.githubusercontent.com/assets/484366/12022821/36e92c6e-ad9c-11e5-89f0-659e0eb8d11c.png)

Regards,
Sergey

**Comment by ypavlotsky** [comment]
Hi,

The easiest way to do this is to have a VMAP response that has your overlay ads and midrolls in it. Then the SDK will handle all of the details of displaying the ads.

**Comment by onix-sergey** [comment]
hi,

It not works like expected. How to do it manually? in other words, how to get "OverlayAdContainer"(width, height and manager/handlers)? 

thanks.

**Comment by ypavlotsky** [comment]
The videojs-ima plugin isn't designed to make manual ad requests for a single content video. For multiple ads, it's recommended to use VMAP. What's the issue you're having with the VMAP?

**Comment by jnthnclrk** [comment]
Don't you just specify overlays in DFP?

<img width="576" alt="screenshot 2018-07-12 12 52 40" src="https://user-images.githubusercontent.com/498192/42647650-8f036b92-85d2-11e8-9ae6-4c4e018616ba.png">

**Comment by onix-sergey** [comment]
> What's the issue you're having with the VMAP?
few technical issue(like ad is loaded, but not played), but the most important that it is shows lower cpm if compare with direct call.

> Don't you just specify overlays in DFP?
yes, but sometime it show full-area overlay. Currently issue solved by override requestAds for overlay request to not ask the linear ad. 
and issue left with autoPlayAdBreaks, if it's enabled then non-linear ads are not shown... just fire a ready event... but if changed  autoPlayAdBreaks to false and call playAdBreak then it shows...

**Comment by jnthnclrk** [comment]
Do I have this right?

An **overlay non-linear** is a display ad floating over content (like YouTube).
And **overlay linear** is a display ad floating over a background obstructing content (not like YouTube).

**Comment by onix-sergey** [comment]
yes, linear ads shows during a break(if no bugs :) ) in video content, non-linear - during video playback.

**Comment by ypavlotsky** [comment]
Sorry, I'm still not sure what errors you're seeing. Do you have a test page I can take a look at and see if I can replicate the issue?

**Comment by priyankasinghr** [comment]
@ypavlotsky We've defined the "breatype=nonlinear" in our VMAP XML and also setup overlay ads, but we still see linear overlay ads serving instead of non-linear ad, like this: https://prnt.sc/k6gd6e
Can you suggest what can be done here to ensure it returns only non-linear overlay ads.
I've also found [this support doc](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility#vmap-footnote) that mentions that overlay ads are not yet supported for VMAP which makes it more confusing.

**Comment by ypavlotsky** [comment]
I would double-check the serving configuration to make sure the individual non-linear ads are correctly set up as overlays. Unfortunately, I can't help you debug your serving configuration, but I'd suggest going to the [DFP help forums](https://productforums.google.com/forum/#!forum/dfp).

**Comment by priyankasinghr** [comment]
Sure, I've checked the setup already. Just to confirm, can the linear ads serve even if the 'breaktype=nonlinear' is set in the VMAP XML?

**Comment by ypavlotsky** [comment]
I believe so, at least according to my testing, it seems so.

**Comment by jnthnclrk** [comment]
@priyankasinghr I often see linear ads and in-stream on our pre-roll call set to nonlinear.

**Comment by Kiro705** [comment]
Hi @priyankasinghr and @onix-sergey ,

It looks as though your issues were resolved so I will be closing this issue, but please reopen it if that is not the case.
